#!/usr/bin/env python3
"""Which half-select SEQUENCES does a real update fire, and how often?

Two things are joined here.

1. The attractor sweep (seq_attractor.csv) showed that a half-select only
   moves charge as an ORDERED PAIR applied back-to-back.  Eight of the sixteen
   pairs drive the cell to a fixed level regardless of where it started; the
   other eight leave it wherever it was.  Class and level are read off that
   data rather than hardcoded.

2. The random-signed u,v run recorded only aggregate exposure counts
   (H_N1..H_N4), which cannot distinguish N1-then-N2 from N2-then-N1.  The
   ordering lives in the bit streams, so those are regenerated by replaying
   the same seeded RNG in the same call order as uv_random_signed.py.  The
   replay is checked against the u,v stored in the CSV on every trial.

WHAT COUNTS AS THE CELL'S STATE, per the firmware
-------------------------------------------------
apply_potentiation_pulses drives every slot as

    clear all N1,N2 -> set N1 mask -> set N2 mask -> clear N2 -> clear N1

so within a slot N1 rises first and N2 falls first.  The transistor left on
LAST -- the one that defines the state the cell carries into the next slot --
is therefore the ROW line whenever the row bit is 1, regardless of the column
bit.  A coincidence slot (both 1) is no exception: N2 is cleared before N1, so
a coincidence also ends with the row line as the last-on transistor.
apply_depression_pulses has the identical structure with N3/N4.

That gives the per-slot last-on transistor:

    row=1, col=0  ->  row line   (N1 / N3)   half-select
    row=1, col=1  ->  row line   (N1 / N3)   coincidence, still ends on row
    row=0, col=1  ->  col line   (N2 / N4)   half-select
    row=0, col=0  ->  unchanged, the cell keeps whatever it was holding

An ordered pair is registered when the last-on transistor CHANGES from the
previous state.  Empty slots do not clear the state, so the pair spans them.

CROSSING QUADRANT BOUNDARIES
----------------------------
The state persists across the four quadrant commands of one trial: a cell
left on N1 by the potentiation command and then driven by N4 in the following
depression command sees the ordered pair N1+N4.  Those cross-quadrant pairs
are exactly what the previous version of this script missed, and they are the
ones that reach the reset-like attractors.  State is carried across quadrants
within a trial and cleared by the hard reset between trials.
"""
import csv
import glob
import sys
from collections import Counter, defaultdict

import numpy as np

N = 5
BL = 10
SEED = 0
STARTS = ["full_pot", "mid_pot", "reset", "mid_dep", "full_dep"]
SPREAD_CONVERGED = 250      # LSB; inert pairs keep the full ~900 range


def classify_pairs():
    """Label each ordered pair from the attractor sweep.

    Converging = the five starting states collapse to a common level by the
    longest cycle count measured; the attractor is the mean of the endpoints.
    """
    rows = []
    files = sorted(glob.glob("*_seq_attractor.csv"))
    for p in files:
        rows += list(csv.DictReader(open(p, encoding="utf-8")))
    out = {}
    for combo in sorted({r["combo"] for r in rows}):
        if combo == "control":
            continue
        sub = [r for r in rows if r["combo"] == combo]
        mx = max(int(r["cycles"]) for r in sub)
        ends = []
        for s in STARTS:
            v = [float(r["after"]) for r in sub
                 if r["start"] == s and int(r["cycles"]) == mx]
            if v:
                ends.append(np.mean(v))
        if len(ends) < 2:
            continue
        spread = max(ends) - min(ends)
        out[combo] = dict(spread=spread, level=float(np.mean(ends)),
                          converging=spread < SPREAD_CONVERGED, cycles=mx,
                          ends=ends)
    return out, files


def streams(mask, probs, rng):
    """Same call pattern as uv_random_signed.streams -- order matters."""
    return [(rng.random(BL) < probs[k]).astype(int) if mask[k]
            else np.zeros(BL, int) for k in range(N)]


def last_on(rbit, cbit, rline, cline):
    """Transistor still on at the end of this slot, or None if idle.

    The row line is cleared last, so any slot with the row bit set ends on the
    row line -- coincidence slots included.
    """
    if rbit:
        return rline
    if cbit:
        return cline
    return None


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else sorted(
        glob.glob("*_uv_random_signed.csv"))[-1]
    rows = list(csv.DictReader(open(path, encoding="utf-8")))
    trials = sorted({int(r["trial"]) for r in rows})
    by = {(int(r["trial"]), int(r["cell_row"]), int(r["cell_col"])): r
          for r in rows}

    cls, afiles = classify_pairs()
    print(f"attractor classification from {', '.join(afiles)}")
    print(f"  {'pair':7s} {'spread':>8s} {'level':>8s}  class")
    for k, d in sorted(cls.items(), key=lambda kv: -kv[1]["level"]):
        tag = "CONVERGING" if d["converging"] else "inert"
        print(f"  {k:7s} {d['spread']:8.0f} {d['level']:+8.0f}  {tag}")
    active = {k for k, d in cls.items() if d["converging"]}

    # --- replay the RNG and walk the slots, carrying state ----------------
    rng = np.random.default_rng(SEED)
    cellpairs = defaultdict(Counter)
    cross = Counter()          # pairs that span two quadrant commands
    within = Counter()
    coin_broke = 0             # times a coincidence slot changed the state
    for t in trials:
        u = rng.uniform(-1, 1, N)
        v = rng.uniform(-1, 1, N)
        chk = by[(t, 1, 1)]
        assert abs(float(chk["u"]) - u[0]) < 1e-9, f"replay drift trial {t}"
        assert abs(float(chk["v"]) - v[0]) < 1e-9, f"replay drift trial {t}"
        pu, pv = np.abs(u), np.abs(v)

        # hard reset before each trial leaves no line asserted
        state = {(r, c): None for r in range(N) for c in range(N)}

        quads = [("POTENTIATION", u > 0, v > 0), ("POTENTIATION", u < 0, v < 0),
                 ("DEPRESSION", u > 0, v < 0), ("DEPRESSION", u < 0, v > 0)]
        for qi, (mode, rmask, cmask) in enumerate(quads):
            if not (rmask.any() and cmask.any()):
                continue
            n1 = streams(rmask, pu, rng)
            n2 = streams(cmask, pv, rng)
            rl, cl = ("N1", "N2") if mode == "POTENTIATION" else ("N3", "N4")
            for r in range(N):
                for c in range(N):
                    first = True
                    for k in range(BL):
                        cur = last_on(n1[r][k], n2[c][k], rl, cl)
                        if cur is None:
                            continue          # idle slot: state persists
                        prev = state[(r, c)]
                        if prev is not None and prev != cur:
                            cellpairs[(t, r + 1, c + 1)][f"{prev}+{cur}"] += 1
                            if first:
                                cross[f"{prev}+{cur}"] += 1
                            else:
                                within[f"{prev}+{cur}"] += 1
                            if n1[r][k] and n2[c][k]:
                                coin_broke += 1
                        state[(r, c)] = cur
                        first = False

    dirs = {k: ("pot" if float(r["desired"]) > 0 else
                ("dep" if float(r["desired"]) < 0 else "zero"))
            for k, r in by.items()}

    order = sorted(cls, key=lambda k: (k not in active, -cls[k]["level"]))
    tot = Counter()
    bydir = {k: Counter() for k in ("pot", "dep", "zero")}
    ncell = {k: 0 for k in ("pot", "dep", "zero")}
    for key, cnt in cellpairs.items():
        tot += cnt
        bydir[dirs[key]] += cnt
    for key in by:
        ncell[dirs[key]] += 1

    ncells = len(by)
    print(f"\n\nordered half-select sequences fired during the update run")
    print(f"({len(trials)} trials x 25 cells = {ncells} cell-updates, "
          f"bit_length {BL}, state carried across quadrants)\n")
    hdr = (f"{'pair':7s} {'class':>11s} {'level':>7s} | {'total':>7s} "
           f"{'/cell':>6s} {'cross':>6s} | {'pot':>6s} {'/cell':>6s} | "
           f"{'dep':>6s} {'/cell':>6s} | {'zero':>5s}")
    print(hdr)
    print("-" * len(hdr))
    for k in order:
        d = cls[k]
        tag = "CONVERGING" if k in active else "inert"
        print(f"{k:7s} {tag:>11s} {d['level']:+7.0f} | {tot[k]:7d} "
              f"{tot[k]/ncells:6.2f} {cross[k]:6d} | "
              f"{bydir['pot'][k]:6d} {bydir['pot'][k]/max(ncell['pot'],1):6.2f} | "
              f"{bydir['dep'][k]:6d} {bydir['dep'][k]/max(ncell['dep'],1):6.2f} | "
              f"{bydir['zero'][k]:5d}")

    act_tot = sum(tot[k] for k in active)
    all_tot = sum(tot.values())
    print(f"\ncell-updates by direction: pot {ncell['pot']}, "
          f"dep {ncell['dep']}, zero {ncell['zero']}")
    print(f"total ordered pairs {all_tot} ({all_tot/ncells:.2f} per "
          f"cell-update); active {act_tot} "
          f"({100*act_tot/max(all_tot,1):.1f}%, {act_tot/ncells:.2f} per cell)")
    print(f"cross-quadrant pairs {sum(cross.values())} "
          f"({100*sum(cross.values())/max(all_tot,1):.1f}% of all); "
          f"within-quadrant {sum(within.values())}")
    print(f"coincidence slots that changed the last-on transistor: "
          f"{coin_broke}")

    grp = [("toward +457..+473 (potentiating)",
            [k for k in active if cls[k]["level"] > 200]),
           ("toward ~+25 (reset-like)",
            [k for k in active if -200 <= cls[k]["level"] <= 200]),
           ("toward -417..-428 (depressing)",
            [k for k in active if cls[k]["level"] < -200])]
    print("\nactive pairs grouped by where they pull the cell:")
    for name, ks in grp:
        if not ks:
            continue
        n_p = sum(bydir["pot"][k] for k in ks)
        n_d = sum(bydir["dep"][k] for k in ks)
        print(f"  {name:34s} {','.join(ks):24s} "
              f"pot {n_p/max(ncell['pot'],1):5.2f}/cell   "
              f"dep {n_d/max(ncell['dep'],1):5.2f}/cell")

    out = "halfselect_seq_in_update.csv"
    with open(out, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["trial", "cell_row", "cell_col", "desired", "direction",
                    "delta"] + order
                   + ["active_total", "act_pot", "act_reset", "act_dep"])
        gp = {n: ks for n, ks in grp}
        for (t, r, c), rec in sorted(by.items()):
            cnt = cellpairs[(t, r, c)]
            w.writerow(
                [t, r, c, rec["desired"], dirs[(t, r, c)], rec["delta"]]
                + [cnt[k] for k in order]
                + [sum(cnt[k] for k in active)]
                + [sum(cnt[k] for k in gp["toward +457..+473 (potentiating)"]),
                   sum(cnt[k] for k in gp["toward ~+25 (reset-like)"]),
                   sum(cnt[k] for k in gp["toward -417..-428 (depressing)"])])
    print(f"\nper-cell counts -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
